name = "Foundation"
defaultTargets = ["Foundation"]

[leanOptions]
pp.unicode.fun = true
weak.linter.flexible = true
weak.linter.refine = true
weak.linter.oldObtain = true
weak.linter.style.multiGoal = true

[[lean_lib]]
name = "Foundation"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.33.0"

[[require]]
scope = "leanprover-community"
name = "mathlib"
rev = "v4.33.0"

[[require]]
name = "axiom-audit"
git = "https://github.com/SnO2WMaN/axiom-audit"
rev = "827e715d39231df230cb5b1a200be07c151b323b"
