module

public import Foundation.ProvabilityLogic.Kripke.Basic
public import Mathlib.Data.Fintype.Option

/-!
# Rooted Kripke models

Rooted models, the cone generated by a world, the extension of a rooted model by a new root
below the old one, and the rank of a world and the height of a finite rooted `GL` model.
-/

@[expose] public section

namespace FFL.ProvabilityLogic.Kripke

open Model Model.World

variable {κ α : Type*} [Nonempty κ]

/-- A Kripke model with a root, from which every other world is accessible. -/
structure RootedModel (κ : Type*) [Nonempty κ] (α : Type*) extends Model κ α where
  root : κ
  root_rel : ∀ x, x ≠ root → toModel.Rel root x

/-! ### Cones -/

namespace Model

variable {M : Model κ α} {r x : M.World} {A : Formula α}

instance : Nonempty { x : M.World // x = r ∨ r ≺ x } := ⟨⟨r, .inl rfl⟩⟩

/-- The submodel of the worlds accessible from `r`, rooted at `r`. -/
def cone (M : Model κ α) (r : M.World) : RootedModel { x : M.World // x = r ∨ r ≺ x } α where
  Rel' x y := x.1 ≺ y.1
  Val' x a := M.Val x.1 a
  root := ⟨r, .inl rfl⟩
  root_rel := by
    rintro ⟨x, rfl | h⟩ hx;
    . exact absurd rfl hx;
    . exact h;

instance [M.IsFiniteGL] : (M.cone r).IsFiniteGL where
  trans _ _ _ h₁ h₂ := IsTrans.trans (r := M.Rel) _ _ _ h₁ h₂
  irrefl x := Std.Irrefl.irrefl (r := M.Rel) x.1
  finite := Subtype.finite

lemma forces_cone [IsTrans _ M.Rel] {x : (M.cone r).World} : x ⊩[(M.cone r).toModel] A ↔ x.1 ⊩[M] A := by
  induction A generalizing x with
  | atom | falsum => rfl;
  | imp A B ihA ihB => exact imp_congr ihA ihB;
  | box A ih =>
    obtain ⟨x, hx⟩ := x;
    constructor;
    . intro h y Rxy;
      have hy : y = r ∨ r ≺ y := by
        rcases hx with rfl | hx;
        . exact .inr Rxy;
        . exact .inr (IsTrans.trans _ _ _ hx Rxy);
      exact ih.mp (h ⟨y, hy⟩ Rxy);
    . intro h y Rxy;
      exact ih.mpr (h y.1 Rxy);

end Model

/-! ### Rank and height -/

namespace Model

open Classical

variable {M : Model κ α} [Fintype M.World] [M.IsGL] {x y : M.World} {n : ℕ}

/-- The length of the longest chain from `x`. -/
noncomputable def World.rank (x : M.World) : ℕ := cwfHeight (· ≺ ·) x

lemma rank_lt_of_rel (h : x ≺ y) : y.rank < x.rank := cwfHeight_gt_of h

lemma rank_lt_iff : x.rank < n ↔ ∀ y, ¬x ≺^[n] y := by
  induction n generalizing x with
  | zero => simp;
  | succ n ih =>
    calc
      _ ↔ x.rank ≤ n                 := Nat.lt_add_one_iff
      _ ↔ ∀ y, x ≺ y → y.rank < n    :=
        ⟨fun h _ Rxy ↦ lt_of_lt_of_le (rank_lt_of_rel Rxy) h, cwfHeight_le⟩
      _ ↔ ∀ y, ¬x ≺^[n + 1] y         := by simp only [ih, relItr_succ]; grind;

lemma forces_boxItr_bot_iff : x ⊩[M] □^[n]⊥ ↔ x.rank < n := by
  simp [forces_boxItr, rank_lt_iff];

lemma rank_pos_of_forces_dia {A : Formula α} (h : x ⊩[M] ◇A) : 0 < x.rank := by
  obtain ⟨y, Rxy, -⟩ := forces_dia.mp h;
  exact lt_of_le_of_lt (Nat.zero_le _) (rank_lt_of_rel Rxy);

end Model

namespace RootedModel

variable {M : RootedModel κ α} [Fintype M.World] [M.IsGL] {x : M.World} {n : ℕ}

/-- The height of a finite rooted `GL` model: the rank of its root. -/
noncomputable def height (M : RootedModel κ α) [Fintype M.World] [M.IsGL] : ℕ :=
  Model.World.rank (M := M.toModel) M.root

lemma rank_lt_height (h : M.root ≺ x) : Model.World.rank (M := M.toModel) x < M.height :=
  Model.rank_lt_of_rel h

lemma rank_le_height : Model.World.rank (M := M.toModel) x ≤ M.height := by
  by_cases hx : x = M.root;
  . subst hx; rfl;
  . exact (rank_lt_height (M.root_rel x hx)).le;

lemma root_forces_boxItr_bot_iff : M.root ⊩[M.toModel] □^[n]⊥ ↔ M.height < n :=
  Model.forces_boxItr_bot_iff

end RootedModel

/-! ### Extension by a new root -/

namespace RootedModel

variable (M : RootedModel κ α)

/-- `M` with a new root below the old one, which forces the same atoms as the old root. -/
def extendRoot : RootedModel (Option κ) α where
  Rel' x y := match x, y with
    | some x, some y => M.Rel x y
    | none, some _ => True
    | _, none => False
  Val' x a := match x with
    | some x => M.Val x a
    | none => M.Val M.root a
  root := none
  root_rel x hx := by
    rcases x with _ | x;
    . exact absurd rfl hx;
    . trivial;

namespace extendRoot

variable {M} {x y : M.World} {A : Formula α}

@[simp] lemma rel_some_some : (M.extendRoot.Rel (some x) (some y)) ↔ M.Rel x y := Iff.rfl

@[simp] lemma rel_none_some : M.extendRoot.Rel none (some x) := trivial

@[simp] lemma not_rel_none {x : M.extendRoot.World} : ¬M.extendRoot.Rel x none := by
  rcases x with _ | _ <;> exact id

instance [IsTrans _ M.Rel] : IsTrans _ M.extendRoot.Rel where
  trans x y z := by
    rcases x with _ | x <;> rcases y with _ | y <;> rcases z with _ | z <;>
    simp only [rel_some_some, rel_none_some, not_rel_none, IsEmpty.forall_iff, implies_true,
      forall_const];
    exact IsTrans.trans _ _ _

instance [Std.Irrefl M.Rel] : Std.Irrefl M.extendRoot.Rel where
  irrefl x := by
    rcases x with _ | x;
    . exact not_rel_none;
    . exact Std.Irrefl.irrefl (r := M.Rel) x;

instance [IsConverseWellFounded _ M.Rel] : IsConverseWellFounded _ M.extendRoot.Rel where
  cwf := by
    have hsome : ∀ x : M.World, Acc (flip M.extendRoot.Rel) (some x) := by
      intro x;
      induction x using WellFounded.induction IsConverseWellFounded.cwf (r := flip M.Rel) with
      | h x ih =>
        constructor;
        rintro (_ | y) h;
        . exact absurd h not_rel_none;
        . exact ih y h;
    constructor;
    rintro (_ | x);
    . constructor;
      rintro (_ | y) h;
      . exact absurd h not_rel_none;
      . exact hsome y;
    . exact hsome x;

instance [M.IsGL] : M.extendRoot.IsGL where

instance [Fintype M.World] : Fintype M.extendRoot.World := inferInstanceAs (Fintype (Option κ))

lemma forces_some : some x ⊩[M.extendRoot.toModel] A ↔ x ⊩[M.toModel] A := by
  induction A generalizing x with
  | atom | falsum => rfl;
  | imp A B ihA ihB => exact imp_congr ihA ihB;
  | box A ih =>
    constructor;
    . intro h y Rxy;
      exact ih.mp (h (some y) Rxy);
    . rintro h (_ | y) Rxy;
      . exact absurd Rxy not_rel_none;
      . exact ih.mpr (h y Rxy);

lemma relItr_some_iff {n : ℕ} {y : M.extendRoot.World} :
    M.extendRoot.RelItr n (some x) y ↔ ∃ y', y = some y' ∧ M.RelItr n x y' := by
  induction n generalizing x with
  | zero => simp [eq_comm];
  | succ n ih =>
    simp only [Model.relItr_succ];
    constructor;
    . rintro ⟨(_ | z), Rxz, Rzy⟩;
      . exact absurd Rxz not_rel_none;
      . obtain ⟨y', rfl, h⟩ := ih.mp Rzy;
        exact ⟨y', rfl, z, Rxz, h⟩;
    . rintro ⟨y', rfl, z, Rxz, Rzy⟩;
      exact ⟨some z, Rxz, ih.mpr ⟨y', rfl, Rzy⟩⟩;

variable [Fintype M.World] [M.IsGL]

lemma rank_some : Model.World.rank (M := M.extendRoot.toModel) (some x) = Model.World.rank (M := M.toModel) x := by
  have h : ∀ n, Model.World.rank (M := M.extendRoot.toModel) (some x) < n ↔
      Model.World.rank (M := M.toModel) x < n := by
    intro n;
    simp only [Model.rank_lt_iff, relItr_some_iff];
    grind;
  exact le_antisymm (Nat.le_of_lt_succ ((h _).mpr (Nat.lt_succ_self _)))
    (Nat.le_of_lt_succ ((h _).mp (Nat.lt_succ_self _)));

lemma height_extendRoot : M.extendRoot.height = M.height + 1 := by
  apply le_antisymm;
  . apply cwfHeight_le;
    rintro (_ | y) h;
    . exact absurd h not_rel_none;
    . have := rank_some (M := M) (x := y);
      have := RootedModel.rank_le_height (M := M) (x := y);
      simp only [Model.World.rank] at *;
      omega;
  . exact Nat.succ_le_of_lt <| lt_cwfHeight (b := some M.root) trivial <| by
      have := rank_some (M := M) (x := M.root);
      simp only [RootedModel.height, Model.World.rank] at *;
      omega;

end extendRoot

end RootedModel

end FFL.ProvabilityLogic.Kripke

end
