module

public import Foundation.Vorspiel.Order.BooleanAlgebra.Lemmata
public import Mathlib.Order.BooleanSubalgebra
public import Mathlib.Data.Set.Finite.Basic

/-!
# Adjoining a single element to a Boolean subalgebra

A normal-form description of `BooleanSubalgebra.closure (insert a A)`: every element of
the subalgebra generated by `A` together with a new element `a` is of the form
`(y ⊓ a) ⊔ (z ⊓ aᶜ)` for `y z ∈ A`. In particular, adjoining one element to a finite
subalgebra yields another finite subalgebra.

Folklore Boolean algebra fact; there is no direct literature source.
-/

@[expose] public section

namespace BooleanSubalgebra

variable {α : Type*} [BooleanAlgebra α] {A : BooleanSubalgebra α} {a x : α}

/-- Normal form for elements of the Boolean subalgebra generated by `A ∪ {a}`. -/
theorem mem_closure_insert :
    x ∈ closure (insert a (A : Set α)) ↔
      ∃ y ∈ A, ∃ z ∈ A, x = (y ⊓ a) ⊔ (z ⊓ aᶜ) := by
  sorry

/-- Adjoining a single element to a finite Boolean subalgebra keeps it finite. -/
lemma closure_insert_finite (hA : (A : Set α).Finite) (a : α) :
    ((closure (insert a (A : Set α)) : BooleanSubalgebra α) : Set α).Finite := by
  sorry

/-- The original subalgebra embeds into the one generated by adjoining an element. -/
lemma le_closure_insert : A ≤ closure (insert a (A : Set α)) := by
  sorry

/-- The adjoined element itself belongs to the generated subalgebra. -/
lemma self_mem_closure_insert : a ∈ closure (insert a (A : Set α)) := by
  sorry

end BooleanSubalgebra
