module

public import Foundation.Vorspiel.Order.BooleanAlgebra.Lemmata
public import Foundation.Vorspiel.Order.BooleanAlgebra.ClosureInsert
public import Foundation.Vorspiel.Order.BooleanAlgebra.Companion

/-!
# Extending a partial isomorphism by one element

Given `e : A ≃o B` and a companion `b` of `a` under `e` (see `IsCompanion`), the
isomorphism `e` extends to an order isomorphism between the subalgebras generated by
`A ∪ {a}` and `B ∪ {b}`. Together with `exists_isCompanion`, this is the extension step
of the back-and-forth construction in
`Foundation.Vorspiel.Order.BooleanAlgebra.Iso`. We also record the trivial base case:
the (unique) bottom Boolean subalgebra of a nontrivial Boolean algebra is order
isomorphic to that of any other nontrivial Boolean algebra.

Folklore Boolean algebra fact underlying the back-and-forth method; there is no direct
literature source.
-/

@[expose] public section

open BooleanSubalgebra

noncomputable section

variable {α β : Type*} [BooleanAlgebra α] [BooleanAlgebra β]
  {A : BooleanSubalgebra α} {B : BooleanSubalgebra β} {e : A ≃o B} {a : α} {b : β}

/-- Companions congrue: comparing normal-form representatives on the `A`-side transports
along `e` to comparing the corresponding normal-form representatives on the `B`-side. -/
lemma IsCompanion.map_le_map (h : IsCompanion e a b) {y₁ z₁ y₂ z₂ : A}
    (hle : ((y₁ : α) ⊓ a) ⊔ ((z₁ : α) ⊓ aᶜ) ≤ ((y₂ : α) ⊓ a) ⊔ ((z₂ : α) ⊓ aᶜ)) :
    ((e y₁ : β) ⊓ b) ⊔ ((e z₁ : β) ⊓ bᶜ) ≤ ((e y₂ : β) ⊓ b) ⊔ ((e z₂ : β) ⊓ bᶜ) := by
  sorry

/-- Given a companion `b` of `a` under `e`, extend `e` to an order isomorphism between the
subalgebras generated by adjoining `a` (resp. `b`) to `A` (resp. `B`). -/
def IsCompanion.extend (h : IsCompanion e a b) :
    (closure (insert a (A : Set α)) : BooleanSubalgebra α) ≃o
      (closure (insert b (B : Set β)) : BooleanSubalgebra β) := by
  sorry

/-- Every element of `closure (insert a A)` has a normal-form representative whose image
under `IsCompanion.extend` is described by the corresponding representative on the
`B`-side. -/
lemma IsCompanion.extend_spec (h : IsCompanion e a b)
    (x : (closure (insert a (A : Set α)) : BooleanSubalgebra α)) :
    ∃ y z : A, (x : α) = ((y : α) ⊓ a) ⊔ ((z : α) ⊓ aᶜ) ∧
      (h.extend x : β) = ((e y : β) ⊓ b) ⊔ ((e z : β) ⊓ bᶜ) := by
  sorry

/-- `IsCompanion.extend` agrees with `e` on the original subalgebra `A`. -/
lemma IsCompanion.extend_coe (h : IsCompanion e a b) (x : A) :
    (h.extend ⟨x, le_closure_insert x.2⟩ : β) = e x := by
  sorry

/-- `IsCompanion.extend` sends the adjoined element `a` to its companion `b`. -/
lemma IsCompanion.extend_self (h : IsCompanion e a b) :
    (h.extend ⟨a, self_mem_closure_insert⟩ : β) = b := by
  sorry

/-- The bottom Boolean subalgebras of two nontrivial Boolean algebras are order
isomorphic (both are two-element chains `{⊥, ⊤}`). -/
def botOrderIso [Nontrivial α] [Nontrivial β] :
    (⊥ : BooleanSubalgebra α) ≃o (⊥ : BooleanSubalgebra β) := by
  sorry

end
