module

public import Foundation.Vorspiel.Order.BooleanAlgebra.Basic
public import Mathlib.Order.BooleanSubalgebra
public import Mathlib.Data.Set.Finite.Basic

/-!
# Extending a partial isomorphism by one element

The single-step extension lemma of the back-and-forth construction in
`Foundation.Vorspiel.Order.BooleanAlgebra.Iso`, in three parts:

* A normal-form description of `BooleanSubalgebra.closure (insert a A)`: every element
  of the subalgebra generated by `A` together with a new element `a` is of the form
  `(y ⊓ a) ⊔ (z ⊓ aᶜ)` for `y z ∈ A`. In particular, adjoining one element to a finite
  subalgebra keeps it finite.
* Given a finite Boolean subalgebra `A ≤ α`, an order isomorphism `e : A ≃o B` onto a
  subalgebra `B ≤ β`, and an element `a : α`, a *companion* of `a` under `e` is an
  element `b : β` playing the same role with respect to `B` as `a` does with respect to
  `A`: for every `w : A`, `w` is disjoint from (resp. below) `a` iff `e w` is disjoint
  from (resp. below) `b`. When `β` is atomless every element admits a companion.
* Given a companion `b` of `a` under `e`, `e` extends to an order isomorphism between
  the subalgebras generated by adjoining `a` (resp. `b`) to `A` (resp. `B`). We also
  record the trivial base case: the (unique) bottom Boolean subalgebra of a nontrivial
  Boolean algebra is order isomorphic to that of any other nontrivial Boolean algebra.

Folklore Boolean algebra facts underlying the back-and-forth method; there is no direct
literature source.
-/

@[expose] public section

namespace BooleanSubalgebra

variable {α : Type*} [BooleanAlgebra α] {A : BooleanSubalgebra α} {a x : α}

/-- Normal form for elements of the Boolean subalgebra generated by `A ∪ {a}`. -/
theorem mem_closure_insert :
    x ∈ closure (insert a (A : Set α)) ↔
      ∃ y ∈ A, ∃ z ∈ A, x = (y ⊓ a) ⊔ (z ⊓ aᶜ) := by
  sorry

/-- Adjoining a single element to a finite Boolean subalgebra keeps it finite. -/
lemma closure_insert_finite (hA : (A : Set α).Finite) (a : α) :
    ((closure (insert a (A : Set α)) : BooleanSubalgebra α) : Set α).Finite := by
  sorry

/-- The original subalgebra embeds into the one generated by adjoining an element. -/
lemma le_closure_insert : A ≤ closure (insert a (A : Set α)) := by
  sorry

/-- The adjoined element itself belongs to the generated subalgebra. -/
lemma self_mem_closure_insert : a ∈ closure (insert a (A : Set α)) := by
  sorry

end BooleanSubalgebra

open BooleanSubalgebra

variable {α β : Type*} [BooleanAlgebra α] [BooleanAlgebra β]
  {A : BooleanSubalgebra α} {B : BooleanSubalgebra β}

/-- `b` is a companion of `a` under `e : A ≃o B`: every `w : A` relates to `a` (by
disjointness or by `≤`) exactly as `e w` relates to `b`. -/
def IsCompanion (e : A ≃o B) (a : α) (b : β) : Prop :=
  ∀ w : A, ((w : α) ⊓ a = ⊥ ↔ (e w : β) ⊓ b = ⊥) ∧ ((w : α) ≤ a ↔ (e w : β) ≤ b)

variable {e : A ≃o B} {a : α} {b : β}

/-- The companion relation is symmetric under swapping `e` for `e.symm`. -/
lemma IsCompanion.symm (h : IsCompanion e a b) : IsCompanion e.symm b a := by
  sorry

/-- If `A` is finite and `β` is a nontrivial densely ordered (equivalently, atomless)
Boolean algebra, every `a : α` admits a companion under `e`. -/
theorem exists_isCompanion [Nontrivial β] [DenselyOrdered β]
    (hA : (A : Set α).Finite) (e : A ≃o B) (a : α) :
    ∃ b : β, IsCompanion e a b := by
  sorry

noncomputable section

/-- Companions congrue: comparing normal-form representatives on the `A`-side transports
along `e` to comparing the corresponding normal-form representatives on the `B`-side. -/
lemma IsCompanion.map_le_map (h : IsCompanion e a b) {y₁ z₁ y₂ z₂ : A}
    (hle : ((y₁ : α) ⊓ a) ⊔ ((z₁ : α) ⊓ aᶜ) ≤ ((y₂ : α) ⊓ a) ⊔ ((z₂ : α) ⊓ aᶜ)) :
    ((e y₁ : β) ⊓ b) ⊔ ((e z₁ : β) ⊓ bᶜ) ≤ ((e y₂ : β) ⊓ b) ⊔ ((e z₂ : β) ⊓ bᶜ) := by
  sorry

/-- Given a companion `b` of `a` under `e`, extend `e` to an order isomorphism between the
subalgebras generated by adjoining `a` (resp. `b`) to `A` (resp. `B`). -/
def IsCompanion.extend (h : IsCompanion e a b) :
    (closure (insert a (A : Set α)) : BooleanSubalgebra α) ≃o
      (closure (insert b (B : Set β)) : BooleanSubalgebra β) := by
  sorry

/-- Every element of `closure (insert a A)` has a normal-form representative whose image
under `IsCompanion.extend` is described by the corresponding representative on the
`B`-side. -/
lemma IsCompanion.extend_spec (h : IsCompanion e a b)
    (x : (closure (insert a (A : Set α)) : BooleanSubalgebra α)) :
    ∃ y z : A, (x : α) = ((y : α) ⊓ a) ⊔ ((z : α) ⊓ aᶜ) ∧
      (h.extend x : β) = ((e y : β) ⊓ b) ⊔ ((e z : β) ⊓ bᶜ) := by
  sorry

/-- `IsCompanion.extend` agrees with `e` on the original subalgebra `A`. -/
lemma IsCompanion.extend_coe (h : IsCompanion e a b) (x : A) :
    (h.extend ⟨x, le_closure_insert x.2⟩ : β) = e x := by
  sorry

/-- `IsCompanion.extend` sends the adjoined element `a` to its companion `b`. -/
lemma IsCompanion.extend_self (h : IsCompanion e a b) :
    (h.extend ⟨a, self_mem_closure_insert⟩ : β) = b := by
  sorry

/-- The bottom Boolean subalgebras of two nontrivial Boolean algebras are order
isomorphic (both are two-element chains `{⊥, ⊤}`). -/
def botOrderIso [Nontrivial α] [Nontrivial β] :
    (⊥ : BooleanSubalgebra α) ≃o (⊥ : BooleanSubalgebra β) := by
  sorry

end
