module

public import Foundation.Vorspiel.Order.BooleanAlgebra.Basic
public import Mathlib.Order.BooleanSubalgebra
public import Mathlib.Data.Set.Finite.Basic

/-!
# Extending a partial isomorphism by one element

The single-step extension lemma of the back-and-forth construction in
`Foundation.Vorspiel.Order.BooleanAlgebra.Iso`: every element of the Boolean subalgebra
generated by `A` together with a new element `a` has the normal form `(y ⊓ a) ⊔ (z ⊓ aᶜ)`
with `y z ∈ A`, an atomless target algebra provides a companion for `a`, and a companion
lets one extend an order isomorphism `A ≃o B` across the adjoined element.

Folklore Boolean algebra facts underlying the back-and-forth method; there is no direct
literature source.
-/

@[expose] public section

namespace BooleanAlgebra

variable {γ : Type*} [BooleanAlgebra γ]

lemma eq_insertRep_self (x a : γ) : x = (x ⊓ a) ⊔ (x ⊓ aᶜ) := by
  rw [← inf_sup_left, sup_compl_eq_top, inf_top_eq]

lemma sup_insertRep (y₁ z₁ y₂ z₂ a : γ) :
    ((y₁ ⊓ a) ⊔ (z₁ ⊓ aᶜ)) ⊔ ((y₂ ⊓ a) ⊔ (z₂ ⊓ aᶜ)) = ((y₁ ⊔ y₂) ⊓ a) ⊔ ((z₁ ⊔ z₂) ⊓ aᶜ) := by
  simp [inf_sup_right]
  ac_rfl

lemma inf_insertRep (y₁ z₁ y₂ z₂ a : γ) :
    ((y₁ ⊓ a) ⊔ (z₁ ⊓ aᶜ)) ⊓ ((y₂ ⊓ a) ⊔ (z₂ ⊓ aᶜ)) = ((y₁ ⊓ y₂) ⊓ a) ⊔ ((z₁ ⊓ z₂) ⊓ aᶜ) := by
  have h₁ : y₁ ⊓ a ⊓ (z₂ ⊓ aᶜ) = ⊥ := by
    calc y₁ ⊓ a ⊓ (z₂ ⊓ aᶜ) = (y₁ ⊓ z₂) ⊓ (a ⊓ aᶜ) := by ac_rfl
    _ = ⊥ := by simp
  have h₂ : z₁ ⊓ aᶜ ⊓ (y₂ ⊓ a) = ⊥ := by
    calc z₁ ⊓ aᶜ ⊓ (y₂ ⊓ a) = (z₁ ⊓ y₂) ⊓ (a ⊓ aᶜ) := by ac_rfl
    _ = ⊥ := by simp
  rw [inf_sup_right, inf_sup_left, inf_sup_left, h₁, h₂]
  simp only [sup_bot_eq, bot_sup_eq]
  congr 1 <;> ac_rfl

end BooleanAlgebra

namespace BooleanSubalgebra

variable {α : Type*} [BooleanAlgebra α] {A : BooleanSubalgebra α} {a x : α}

variable (A a) in
/-- The set of normal-form representatives `(y ⊓ a) ⊔ (z ⊓ aᶜ)` with `y z ∈ A`, viewed as a
Boolean subalgebra. By `BooleanSubalgebra.mem_closure_insert` it is the subalgebra generated
by `A ∪ {a}`. -/
def insertRep : BooleanSubalgebra α where
  carrier := {x | ∃ y ∈ A, ∃ z ∈ A, x = (y ⊓ a) ⊔ (z ⊓ aᶜ)}
  supClosed' := by
    rintro _ ⟨y₁, hy₁, z₁, hz₁, rfl⟩ _ ⟨y₂, hy₂, z₂, hz₂, rfl⟩
    exact ⟨_, sup_mem hy₁ hy₂, _, sup_mem hz₁ hz₂, BooleanAlgebra.sup_insertRep ..⟩
  infClosed' := by
    rintro _ ⟨y₁, hy₁, z₁, hz₁, rfl⟩ _ ⟨y₂, hy₂, z₂, hz₂, rfl⟩
    exact ⟨_, inf_mem hy₁ hy₂, _, inf_mem hz₁ hz₂, BooleanAlgebra.inf_insertRep ..⟩
  compl_mem' := by
    rintro _ ⟨y, hy, z, hz, rfl⟩
    exact ⟨_, compl_mem hy, _, compl_mem hz, BooleanAlgebra.compl_insertRep ..⟩
  bot_mem' := ⟨⊥, bot_mem, ⊥, bot_mem, by simp⟩

theorem mem_closure_insert :
    x ∈ closure (insert a (A : Set α)) ↔
      ∃ y ∈ A, ∃ z ∈ A, x = (y ⊓ a) ⊔ (z ⊓ aᶜ) := by
  refine ⟨fun hx => closure_le (L := insertRep A a) |>.2 ?_ hx, ?_⟩
  · rintro w (rfl | hw)
    · exact ⟨⊤, top_mem, ⊥, bot_mem, by simp⟩
    · exact ⟨w, hw, w, hw, BooleanAlgebra.eq_insertRep_self ..⟩
  · rintro ⟨y, hy, z, hz, rfl⟩
    have ha : a ∈ closure (insert a (A : Set α)) := subset_closure (Set.mem_insert ..)
    have hy' : y ∈ closure (insert a (A : Set α)) := subset_closure (Set.mem_insert_of_mem _ hy)
    have hz' : z ∈ closure (insert a (A : Set α)) := subset_closure (Set.mem_insert_of_mem _ hz)
    exact sup_mem (inf_mem hy' ha) (inf_mem hz' (compl_mem ha))

lemma closure_insert_finite (hA : (A : Set α).Finite) (a : α) :
    ((closure (insert a (A : Set α)) : BooleanSubalgebra α) : Set α).Finite :=
  Set.Finite.subset (hA.biUnion fun y _ => hA.biUnion fun z _ =>
      Set.finite_singleton ((y ⊓ a) ⊔ (z ⊓ aᶜ))) <| by
    rintro x hx
    obtain ⟨y, hy, z, hz, rfl⟩ := mem_closure_insert.mp hx
    exact Set.mem_biUnion hy (Set.mem_biUnion hz rfl)

lemma le_closure_insert : A ≤ closure (insert a (A : Set α)) :=
  (Set.subset_insert a _).trans subset_closure

lemma self_mem_closure_insert : a ∈ closure (insert a (A : Set α)) :=
  subset_closure (Set.mem_insert ..)

end BooleanSubalgebra

open BooleanSubalgebra

variable {α β : Type*} [BooleanAlgebra α] [BooleanAlgebra β]
  {A : BooleanSubalgebra α} {B : BooleanSubalgebra β}

/-- `b` is a companion of `a` under `e : A ≃o B`: every `w : A` relates to `a` (by
disjointness or by `≤`) exactly as `e w` relates to `b`. -/
def IsCompanion (e : A ≃o B) (a : α) (b : β) : Prop :=
  ∀ w : A, ((w : α) ⊓ a = ⊥ ↔ (e w : β) ⊓ b = ⊥) ∧ ((w : α) ≤ a ↔ (e w : β) ≤ b)

variable {e : A ≃o B} {a : α} {b : β}

lemma IsCompanion.symm (h : IsCompanion e a b) : IsCompanion e.symm b a := by
  intro v
  have := h (e.symm v)
  rw [OrderIso.apply_symm_apply] at this
  exact ⟨this.1.symm, this.2.symm⟩

theorem exists_isCompanion [Nontrivial β] [DenselyOrdered β]
    (hA : (A : Set α).Finite) (e : A ≃o B) (a : α) :
    ∃ b : β, IsCompanion e a b := by
  sorry

noncomputable section

lemma IsCompanion.map_le_map (h : IsCompanion e a b) {y₁ z₁ y₂ z₂ : A}
    (hle : ((y₁ : α) ⊓ a) ⊔ ((z₁ : α) ⊓ aᶜ) ≤ ((y₂ : α) ⊓ a) ⊔ ((z₂ : α) ⊓ aᶜ)) :
    ((e y₁ : β) ⊓ b) ⊔ ((e z₁ : β) ⊓ bᶜ) ≤ ((e y₂ : β) ⊓ b) ⊔ ((e z₂ : β) ⊓ bᶜ) := by
  sorry

/-- Given a companion `b` of `a` under `e`, extend `e` to an order isomorphism between the
subalgebras generated by adjoining `a` (resp. `b`) to `A` (resp. `B`). -/
def IsCompanion.extend (h : IsCompanion e a b) :
    (closure (insert a (A : Set α)) : BooleanSubalgebra α) ≃o
      (closure (insert b (B : Set β)) : BooleanSubalgebra β) := by
  sorry

lemma IsCompanion.extend_spec (h : IsCompanion e a b)
    (x : (closure (insert a (A : Set α)) : BooleanSubalgebra α)) :
    ∃ y z : A, (x : α) = ((y : α) ⊓ a) ⊔ ((z : α) ⊓ aᶜ) ∧
      (h.extend x : β) = ((e y : β) ⊓ b) ⊔ ((e z : β) ⊓ bᶜ) := by
  sorry

lemma IsCompanion.extend_coe (h : IsCompanion e a b) (x : A) :
    (h.extend ⟨x, le_closure_insert x.2⟩ : β) = e x := by
  sorry

lemma IsCompanion.extend_self (h : IsCompanion e a b) :
    (h.extend ⟨a, self_mem_closure_insert⟩ : β) = b := by
  sorry

def botOrderIso [Nontrivial α] [Nontrivial β] :
    (⊥ : BooleanSubalgebra α) ≃o (⊥ : BooleanSubalgebra β) := by
  sorry

end
