module

public import Foundation.Vorspiel.Order.BooleanAlgebra.Basic
public import Mathlib.Order.BooleanSubalgebra
public import Mathlib.Data.Set.Finite.Basic

/-!
# Extending a partial isomorphism by one element

The single-step extension lemma of the back-and-forth construction in
`Foundation.Vorspiel.Order.BooleanAlgebra.Iso`: every element of the Boolean subalgebra
generated by `A` together with a new element `a` has the normal form `(y ⊓ a) ⊔ (z ⊓ aᶜ)`
with `y z ∈ A`, an atomless target algebra provides a companion for `a`, and a companion
lets one extend an order isomorphism `A ≃o B` across the adjoined element.

Folklore Boolean algebra facts underlying the back-and-forth method; there is no direct
literature source.
-/

@[expose] public section

namespace BooleanAlgebra

variable {γ : Type*} [BooleanAlgebra γ]

lemma eq_insertRep_self (x a : γ) : x = (x ⊓ a) ⊔ (x ⊓ aᶜ) := by
  rw [← inf_sup_left, sup_compl_eq_top, inf_top_eq]

lemma sup_insertRep (y₁ z₁ y₂ z₂ a : γ) :
    ((y₁ ⊓ a) ⊔ (z₁ ⊓ aᶜ)) ⊔ ((y₂ ⊓ a) ⊔ (z₂ ⊓ aᶜ)) = ((y₁ ⊔ y₂) ⊓ a) ⊔ ((z₁ ⊔ z₂) ⊓ aᶜ) := by
  simp [inf_sup_right]
  ac_rfl

lemma inf_insertRep (y₁ z₁ y₂ z₂ a : γ) :
    ((y₁ ⊓ a) ⊔ (z₁ ⊓ aᶜ)) ⊓ ((y₂ ⊓ a) ⊔ (z₂ ⊓ aᶜ)) = ((y₁ ⊓ y₂) ⊓ a) ⊔ ((z₁ ⊓ z₂) ⊓ aᶜ) := by
  have h₁ : y₁ ⊓ a ⊓ (z₂ ⊓ aᶜ) = ⊥ := by
    calc y₁ ⊓ a ⊓ (z₂ ⊓ aᶜ) = (y₁ ⊓ z₂) ⊓ (a ⊓ aᶜ) := by ac_rfl
    _ = ⊥ := by simp
  have h₂ : z₁ ⊓ aᶜ ⊓ (y₂ ⊓ a) = ⊥ := by
    calc z₁ ⊓ aᶜ ⊓ (y₂ ⊓ a) = (z₁ ⊓ y₂) ⊓ (a ⊓ aᶜ) := by ac_rfl
    _ = ⊥ := by simp
  rw [inf_sup_right, inf_sup_left, inf_sup_left, h₁, h₂]
  simp only [sup_bot_eq, bot_sup_eq]
  congr 1 <;> ac_rfl

end BooleanAlgebra

namespace BooleanSubalgebra

variable {α : Type*} [BooleanAlgebra α] {A : BooleanSubalgebra α} {a x : α}

variable (A a) in
/-- The set of normal-form representatives `(y ⊓ a) ⊔ (z ⊓ aᶜ)` with `y z ∈ A`, viewed as a
Boolean subalgebra. By `BooleanSubalgebra.mem_closure_insert` it is the subalgebra generated
by `A ∪ {a}`. -/
def insertRep : BooleanSubalgebra α where
  carrier := {x | ∃ y ∈ A, ∃ z ∈ A, x = (y ⊓ a) ⊔ (z ⊓ aᶜ)}
  supClosed' := by
    rintro _ ⟨y₁, hy₁, z₁, hz₁, rfl⟩ _ ⟨y₂, hy₂, z₂, hz₂, rfl⟩
    exact ⟨_, sup_mem hy₁ hy₂, _, sup_mem hz₁ hz₂, BooleanAlgebra.sup_insertRep ..⟩
  infClosed' := by
    rintro _ ⟨y₁, hy₁, z₁, hz₁, rfl⟩ _ ⟨y₂, hy₂, z₂, hz₂, rfl⟩
    exact ⟨_, inf_mem hy₁ hy₂, _, inf_mem hz₁ hz₂, BooleanAlgebra.inf_insertRep ..⟩
  compl_mem' := by
    rintro _ ⟨y, hy, z, hz, rfl⟩
    exact ⟨_, compl_mem hy, _, compl_mem hz, BooleanAlgebra.compl_insertRep ..⟩
  bot_mem' := ⟨⊥, bot_mem, ⊥, bot_mem, by simp⟩

theorem mem_closure_insert :
    x ∈ closure (insert a (A : Set α)) ↔
      ∃ y ∈ A, ∃ z ∈ A, x = (y ⊓ a) ⊔ (z ⊓ aᶜ) := by
  refine ⟨fun hx => closure_le (L := insertRep A a) |>.2 ?_ hx, ?_⟩
  · rintro w (rfl | hw)
    · exact ⟨⊤, top_mem, ⊥, bot_mem, by simp⟩
    · exact ⟨w, hw, w, hw, BooleanAlgebra.eq_insertRep_self ..⟩
  · rintro ⟨y, hy, z, hz, rfl⟩
    have ha : a ∈ closure (insert a (A : Set α)) := subset_closure (Set.mem_insert ..)
    have hy' : y ∈ closure (insert a (A : Set α)) := subset_closure (Set.mem_insert_of_mem _ hy)
    have hz' : z ∈ closure (insert a (A : Set α)) := subset_closure (Set.mem_insert_of_mem _ hz)
    exact sup_mem (inf_mem hy' ha) (inf_mem hz' (compl_mem ha))

lemma closure_insert_finite (hA : (A : Set α).Finite) (a : α) :
    ((closure (insert a (A : Set α)) : BooleanSubalgebra α) : Set α).Finite :=
  Set.Finite.subset (hA.biUnion fun y _ => hA.biUnion fun z _ =>
      Set.finite_singleton ((y ⊓ a) ⊔ (z ⊓ aᶜ))) <| by
    rintro x hx
    obtain ⟨y, hy, z, hz, rfl⟩ := mem_closure_insert.mp hx
    exact Set.mem_biUnion hy (Set.mem_biUnion hz rfl)

lemma le_closure_insert : A ≤ closure (insert a (A : Set α)) :=
  (Set.subset_insert a _).trans subset_closure

lemma self_mem_closure_insert : a ∈ closure (insert a (A : Set α)) :=
  subset_closure (Set.mem_insert ..)

lemma exists_insertRepPair (u : (closure (insert a (A : Set α)) : BooleanSubalgebra α)) :
    ∃ p : A × A, (u : α) = ((p.1 : α) ⊓ a) ⊔ ((p.2 : α) ⊓ aᶜ) := by
  obtain ⟨y, hy, z, hz, hu⟩ := mem_closure_insert.mp u.2
  exact ⟨(⟨y, hy⟩, ⟨z, hz⟩), hu⟩

/-- A choice of normal-form representative pair, used to define `IsCompanion.extend`. -/
noncomputable def insertRepPair (u : (closure (insert a (A : Set α)) : BooleanSubalgebra α)) :
    A × A :=
  (exists_insertRepPair u).choose

lemma insertRepPair_spec (u : (closure (insert a (A : Set α)) : BooleanSubalgebra α)) :
    (u : α) = (((insertRepPair u).1 : α) ⊓ a) ⊔ (((insertRepPair u).2 : α) ⊓ aᶜ) :=
  (exists_insertRepPair u).choose_spec

end BooleanSubalgebra

open BooleanSubalgebra

variable {α β : Type*} [BooleanAlgebra α] [BooleanAlgebra β]
  {A : BooleanSubalgebra α} {B : BooleanSubalgebra β}

namespace BooleanSubalgebra

@[simp] lemma val_eq_bot {L : BooleanSubalgebra α} {x : L} : (x : α) = ⊥ ↔ x = ⊥ := by
  rw [← val_bot (L := L), Subtype.coe_inj]

lemma val_map_eq_bot (e : A ≃o B) (p : A) : (e p : β) = ⊥ ↔ (p : α) = ⊥ := by
  rw [val_eq_bot, val_eq_bot, ← e.map_bot, EquivLike.apply_eq_iff_eq]

lemma val_map_inf_eq_bot (e : A ≃o B) {p q : A} (h : p ⊓ q = ⊥) :
    (e p : β) ⊓ (e q : β) = ⊥ := by
  have : (e p ⊓ e q : B) = ⊥ := by rw [← e.map_inf, h, e.map_bot]
  simpa using congrArg Subtype.val this

lemma val_map_finsetSup (e : A ≃o B) (s : Finset A) :
    ((e (s.sup id) : B) : β) = s.sup fun p => (e p : β) := by
  classical
  induction s using Finset.induction with
  | empty => simp
  | insert p s _ ih => simp only [Finset.sup_insert, id_eq, e.map_sup, val_sup, ih]

end BooleanSubalgebra

/-- `b` is a companion of `a` under `e : A ≃o B`: every `w : A` relates to `a` (by
disjointness or by `≤`) exactly as `e w` relates to `b`. -/
def IsCompanion (e : A ≃o B) (a : α) (b : β) : Prop :=
  ∀ w : A, ((w : α) ⊓ a = ⊥ ↔ (e w : β) ⊓ b = ⊥) ∧ ((w : α) ≤ a ↔ (e w : β) ≤ b)

variable {e : A ≃o B} {a : α} {b : β}

lemma IsCompanion.symm (h : IsCompanion e a b) : IsCompanion e.symm b a := by
  intro v
  have := h (e.symm v)
  rw [OrderIso.apply_symm_apply] at this
  exact ⟨this.1.symm, this.2.symm⟩

/-- The piece of a companion of `a` lying below `e p`: it vanishes exactly when `p` misses `a`,
and exhausts `e p` exactly when `p` lies below `a`. -/
lemma exists_companionPiece [DenselyOrdered β] (e : A ≃o B) (a : α) (p : A) :
    ∃ c : β, c ≤ (e p : β) ∧ (c = ⊥ ↔ (p : α) ⊓ a = ⊥) ∧ (c = (e p : β) ↔ (p : α) ≤ a) := by
  by_cases h₁ : (p : α) ⊓ a = ⊥
  · refine ⟨⊥, bot_le, iff_of_true rfl h₁, ?_⟩
    rw [eq_comm, val_map_eq_bot]
    exact ⟨fun h => le_of_eq_of_le h bot_le, fun h => by rw [← h₁, inf_eq_left.2 h]⟩
  · by_cases h₂ : (p : α) ≤ a
    · exact ⟨(e p : β), le_rfl,
        ⟨fun h => by rw [val_map_eq_bot] at h; simp [h], fun h => absurd h h₁⟩, iff_of_true rfl h₂⟩
    · obtain ⟨c, hc₁, hc₂⟩ :=
        exists_between (bot_lt_iff_ne_bot.2 fun h => h₁ (by rw [(val_map_eq_bot e p).1 h]; simp))
      exact ⟨c, hc₂.le, iff_of_false hc₁.ne' h₁, iff_of_false hc₂.ne h₂⟩

theorem exists_isCompanion [Nontrivial β] [DenselyOrdered β]
    (hA : (A : Set α).Finite) (e : A ≃o B) (a : α) :
    ∃ b : β, IsCompanion e a b := by
  have : Finite A := hA.to_subtype
  -- `letI` (not `haveI`): the atom lemmas of `Basic` mention `Fintype.ofFinite` in their
  -- statements, so the instance has to stay transparent for them to apply.
  letI := Fintype.ofFinite A
  have hmemw : ∀ {w p : A}, p ∈ BooleanAlgebra.atomsBelow w ↔ IsAtom p ∧ p ≤ w := by
    intro w p; simp [BooleanAlgebra.atomsBelow]
  have hsup : ∀ w : A, ((BooleanAlgebra.atomsBelow w).sup id : A) = w :=
    BooleanAlgebra.sup_atomsBelow_eq
  choose bp hs₁ hs₂ hs₃ using exists_companionPiece e a
  obtain ⟨atoms, hmem⟩ : ∃ s : Finset A, ∀ p, p ∈ s ↔ IsAtom p :=
    ⟨BooleanAlgebra.atomsBelow ⊤, fun p => by simp [hmemw]⟩
  have hX : ∀ p ∈ atoms, (e p : β) ⊓ atoms.sup bp = bp p := fun p hp => by
    rw [Finset.sup_inf_distrib_left]
    refine le_antisymm (Finset.sup_le fun q hq => ?_) ?_
    · rcases eq_or_ne q p with rfl | hqp
      · exact inf_le_right
      · calc (e p : β) ⊓ bp q ≤ (e p : β) ⊓ (e q : β) := inf_le_inf_left _ (hs₁ q)
          _ = ⊥ := val_map_inf_eq_bot e (disjoint_iff.mp
            (((hmem p).1 hp).disjoint_of_ne ((hmem q).1 hq) hqp.symm))
          _ ≤ bp p := bot_le
    · calc bp p = (e p : β) ⊓ bp p := (inf_eq_right.2 (hs₁ p)).symm
        _ ≤ atoms.sup fun q => (e p : β) ⊓ bp q :=
          Finset.le_sup (f := fun q => (e p : β) ⊓ bp q) hp
  refine ⟨atoms.sup bp, fun w => ?_⟩
  have hsub : ∀ p ∈ BooleanAlgebra.atomsBelow w, p ∈ atoms := fun _ hp =>
    (hmem _).2 (hmemw.1 hp).1
  have hvalw : (w : α) = (BooleanAlgebra.atomsBelow w).sup fun p => (p : α) := by
    rw [← val_finsetSup, hsup]
  have hvalew : (e w : β) = (BooleanAlgebra.atomsBelow w).sup fun p => (e p : β) := by
    rw [← val_map_finsetSup e, hsup]
  refine ⟨⟨fun hw => ?_, fun hw => ?_⟩, fun hw => ?_, fun hw => ?_⟩
  · rw [Finset.sup_inf_distrib_left, Finset.sup_eq_bot_iff]
    intro p hp
    rcases BooleanAlgebra.IsAtom.le_or_disjoint ((hmem p).1 hp) w with hle | hdis
    · rw [(hs₂ p).2 (le_bot_iff.1 ((inf_le_inf_right a (show (p : α) ≤ (w : α) from hle)).trans_eq
        hw)), inf_bot_eq]
    · exact le_bot_iff.1 <| (inf_le_inf_left _ (hs₁ p)).trans_eq
        (val_map_inf_eq_bot e (by rwa [inf_comm] at hdis))
  · rw [hvalw, Finset.sup_inf_distrib_right, Finset.sup_eq_bot_iff]
    intro p hp
    refine (hs₂ p).1 (le_bot_iff.1 ?_)
    calc bp p = (e p : β) ⊓ atoms.sup bp := (hX p (hsub p hp)).symm
      _ ≤ (e w : β) ⊓ atoms.sup bp :=
        inf_le_inf_right _ (show (e p : β) ≤ (e w : β) from e.monotone (hmemw.1 hp).2)
      _ = ⊥ := hw
  · rw [hvalew]
    refine Finset.sup_le fun p hp => ?_
    rw [← (hs₃ p).2 (le_trans (show (p : α) ≤ (w : α) from (hmemw.1 hp).2) hw)]
    exact Finset.le_sup (hsub p hp)
  · rw [hvalw]
    refine Finset.sup_le fun p hp => (hs₃ p).1 ?_
    rw [← hX p (hsub p hp), inf_eq_left]
    exact le_trans (show (e p : β) ≤ (e w : β) from e.monotone (hmemw.1 hp).2) hw

noncomputable section

lemma IsCompanion.map_le_map (h : IsCompanion e a b) {y₁ z₁ y₂ z₂ : A}
    (hle : ((y₁ : α) ⊓ a) ⊔ ((z₁ : α) ⊓ aᶜ) ≤ ((y₂ : α) ⊓ a) ⊔ ((z₂ : α) ⊓ aᶜ)) :
    ((e y₁ : β) ⊓ b) ⊔ ((e z₁ : β) ⊓ bᶜ) ≤ ((e y₂ : β) ⊓ b) ⊔ ((e z₂ : β) ⊓ bᶜ) := by
  obtain ⟨h₁, h₂⟩ := BooleanAlgebra.insertRep_le_insertRep_iff.mp hle
  rw [← val_sdiff] at h₁
  rw [← sdiff_eq, sdiff_eq_bot_iff, ← val_sdiff] at h₂
  refine BooleanAlgebra.insertRep_le_insertRep_iff.mpr ⟨?_, ?_⟩
  · rw [← val_sdiff, ← map_sdiff' e]
    exact (h (y₁ \ y₂)).1.mp h₁
  · rw [← val_sdiff, ← map_sdiff' e, ← sdiff_eq, sdiff_eq_bot_iff]
    exact (h (z₁ \ z₂)).2.mp h₂

section

variable {u u₁ u₂ : (closure (insert a (A : Set α)) : BooleanSubalgebra α)}

/-- The underlying map of `IsCompanion.extend`: transport a normal-form representative of `u`
along `e`, `a ↦ b`. The companion hypothesis is not needed to define the map, only to prove
that it is well defined (`IsCompanion.mapRep_eq`). -/
def IsCompanion.mapRep (_h : IsCompanion e a b)
    (u : (closure (insert a (A : Set α)) : BooleanSubalgebra α)) :
    (closure (insert b (B : Set β)) : BooleanSubalgebra β) :=
  ⟨((e (insertRepPair u).1 : β) ⊓ b) ⊔ ((e (insertRepPair u).2 : β) ⊓ bᶜ),
    mem_closure_insert.mpr ⟨_, (e (insertRepPair u).1).2, _, (e (insertRepPair u).2).2, rfl⟩⟩

@[simp] lemma IsCompanion.val_mapRep (h : IsCompanion e a b) : (h.mapRep u : β) =
    ((e (insertRepPair u).1 : β) ⊓ b) ⊔ ((e (insertRepPair u).2 : β) ⊓ bᶜ) := rfl

lemma IsCompanion.mapRep_eq (h : IsCompanion e a b) {y z : A}
    (hu : (u : α) = ((y : α) ⊓ a) ⊔ ((z : α) ⊓ aᶜ)) :
    (h.mapRep u : β) = ((e y : β) ⊓ b) ⊔ ((e z : β) ⊓ bᶜ) := by
  rw [h.val_mapRep]
  exact le_antisymm (h.map_le_map (by rw [← insertRepPair_spec u, hu]))
    (h.map_le_map (by rw [← hu, insertRepPair_spec u]))

lemma IsCompanion.mapRep_mono (h : IsCompanion e a b) (hu : u₁ ≤ u₂) :
    h.mapRep u₁ ≤ h.mapRep u₂ := by
  show (h.mapRep u₁ : β) ≤ (h.mapRep u₂ : β)
  rw [h.val_mapRep, h.val_mapRep]
  exact h.map_le_map (by rw [← insertRepPair_spec u₁, ← insertRepPair_spec u₂]; exact hu)

lemma IsCompanion.mapRep_mapRep (h : IsCompanion e a b) : h.symm.mapRep (h.mapRep u) = u := by
  refine Subtype.ext ?_
  rw [h.symm.mapRep_eq (y := e (insertRepPair u).1) (z := e (insertRepPair u).2) h.val_mapRep,
    OrderIso.symm_apply_apply, OrderIso.symm_apply_apply]
  exact (insertRepPair_spec u).symm

/-- Given a companion `b` of `a` under `e`, extend `e` to an order isomorphism between the
subalgebras generated by adjoining `a` (resp. `b`) to `A` (resp. `B`). -/
def IsCompanion.extend (h : IsCompanion e a b) :
    (closure (insert a (A : Set α)) : BooleanSubalgebra α) ≃o
      (closure (insert b (B : Set β)) : BooleanSubalgebra β) where
  toFun := h.mapRep
  invFun := h.symm.mapRep
  left_inv _ := h.mapRep_mapRep
  right_inv _ := h.symm.mapRep_mapRep
  map_rel_iff' {x₁ x₂} := by
    show h.mapRep x₁ ≤ h.mapRep x₂ ↔ x₁ ≤ x₂
    refine ⟨fun hu => ?_, h.mapRep_mono⟩
    have := h.symm.mapRep_mono hu
    rwa [h.mapRep_mapRep, h.mapRep_mapRep] at this

end

lemma IsCompanion.extend_spec (h : IsCompanion e a b)
    (x : (closure (insert a (A : Set α)) : BooleanSubalgebra α)) :
    ∃ y z : A, (x : α) = ((y : α) ⊓ a) ⊔ ((z : α) ⊓ aᶜ) ∧
      (h.extend x : β) = ((e y : β) ⊓ b) ⊔ ((e z : β) ⊓ bᶜ) :=
  ⟨(insertRepPair x).1, (insertRepPair x).2, insertRepPair_spec x, h.val_mapRep⟩

lemma IsCompanion.extend_coe (h : IsCompanion e a b) (x : A) :
    (h.extend ⟨x, le_closure_insert x.2⟩ : β) = e x := by
  show (h.mapRep ⟨x, le_closure_insert x.2⟩ : β) = e x
  rw [h.mapRep_eq (y := x) (z := x) (BooleanAlgebra.eq_insertRep_self ..)]
  exact (BooleanAlgebra.eq_insertRep_self ..).symm

lemma IsCompanion.extend_self (h : IsCompanion e a b) :
    (h.extend ⟨a, self_mem_closure_insert⟩ : β) = b := by
  show (h.mapRep ⟨a, self_mem_closure_insert⟩ : β) = b
  rw [h.mapRep_eq (y := ⊤) (z := ⊥) (by simp)]
  simp [e.map_top, e.map_bot]

open Classical in
def botOrderIso [Nontrivial α] [Nontrivial β] :
    (⊥ : BooleanSubalgebra α) ≃o (⊥ : BooleanSubalgebra β) where
  toFun x := if (x : α) = ⊥ then ⊥ else ⊤
  invFun v := if (v : β) = ⊥ then ⊥ else ⊤
  left_inv x := Subtype.ext <| by rcases mem_bot.mp x.2 with hx | hx <;> simp [hx]
  right_inv v := Subtype.ext <| by rcases mem_bot.mp v.2 with hv | hv <;> simp [hv]
  map_rel_iff' {x y} := by
    have hβ : ∀ u v : (⊥ : BooleanSubalgebra β), u ≤ v ↔ (u : β) ≤ (v : β) := fun _ _ => Iff.rfl
    have hα : ∀ u v : (⊥ : BooleanSubalgebra α), u ≤ v ↔ (u : α) ≤ (v : α) := fun _ _ => Iff.rfl
    have hcases : ∀ u : (⊥ : BooleanSubalgebra α), u = ⊥ ∨ u = ⊤ := fun u =>
      (mem_bot.mp u.2).imp Subtype.ext Subtype.ext
    have hα' : (⊤ : (⊥ : BooleanSubalgebra α)) ≠ ⊥ := fun hc => by
      simpa using congrArg Subtype.val hc
    rw [hβ, hα]
    rcases hcases x with rfl | rfl <;> rcases hcases y with rfl | rfl <;> simp [hα']

end
