name: Check dependencies consistency

on:
  push:
    branches:
      - "master"
    paths:
      - "lake-manifest.json"
      - "docbuild/lake-manifest.json"
  pull_request:
    paths:
      - "lake-manifest.json"
      - "docbuild/lake-manifest.json"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno run ./scripts/consistent_deps.ts
