name: Documents

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Build project and documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install elan
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - uses: actions/cache@v4
        with:
          path: .lake
          key: docs-lake-${{ runner.os }}-${{ hashFiles('lake-manifest.json') }}
          restore-keys: |
            docs-lake-${{ runner.os }}-${{ hashFiles('lake-manifest.json') }}
            docs-lake-${{ runner.os }}
      - run: lake -R -Kenv=dev exe cache get
      - run: lake -R -Kenv=dev build Logic:docs
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./.lake/build/doc

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs:
      - docs
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docs
          path: ./_site/docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
      - uses: actions/deploy-pages@v4
        id: deployment
