name: Update

on:
  schedule:
    - cron: "0 8 * * 0" # at 08:00 (UTC) on Sunday
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: oliver-butterley/lean-update@v1-alpha
        with:
          on_update_succeeds: pr
          on_update_fails: issue
